from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Any

import time
import numpy as np

from Unit import ILFR


@dataclass
class HDFBLSEnhanceConfig:
    """Configuration of the DET-based enhancement layer."""
    num_fuzzy_set: int = 5        # Very Low, Low, Medium, High, Very High
    elite_width: int = 3          # V_max: maximum number of elite branches per layer
    min_branch_nodes: int = 1     # m_l: lower bound of branch size
    max_branch_nodes: int = 10    # m_u: upper bound of branch size
    max_depth: int = 20           # T_max: maximum tree depth
    patience: int = 5             # P_max: early stopping patience
    random_state: int = 2026

class HDFBLSEnhanceNode:
    """
    Enhancement layer of HDFBLS.

    This module implements the Dynamic Elite Tree (DET).
    It constructs composite fuzzy rules over the basic rule activations F,
    and selects high-scoring branch-node combinations layer by layer.
    """

    def __init__(
        self,
        inp_nodes: int,
        config: Optional[HDFBLSEnhanceConfig] = None,
    ):
        self.inp_nodes = int(inp_nodes)
        self.cfg = config or HDFBLSEnhanceConfig()
        self.rng = np.random.default_rng(self.cfg.random_state)

        self.W_: Optional[np.ndarray] = None
        self.blocks_meta: list[dict[str, Any]] = []
        self.elite_tree_: list[list[dict[str, Any]]] = []

        self.best_score_: float = 0.0
        self.best_node_depth: int = 0
        self.best_node_total_nodes: int = 0
        self.enhancement_time: float = 0.0
        self.S_expected_: int = 0

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def train_enhancement_incremental(
        self,
        F_train: np.ndarray,
        Y_train: np.ndarray,
        max_depth: Optional[int] = None,
    ):
        """
        Train the DET enhancement layer.

        Parameters
        ----------
        F_train : array, shape (N, R)
            Basic fuzzy rule firing-strength matrix generated by ARGS.
        Y_train : array, shape (N, C)
            One-hot encoded training labels.
        max_depth : int, optional
            Maximum DET depth. If None, use config.max_depth.

        Returns
        -------
        A_best, A_best_pinv, W_best
            The selected model matrix, its pseudoinverse, and output weights.
        """
        F_train = np.asarray(F_train, dtype=np.float64)
        Y_train = np.asarray(Y_train, dtype=np.float64)

        if F_train.ndim != 2:
            raise ValueError(f"F_train must be 2-D, but got shape {F_train.shape}.")
        if Y_train.ndim != 2:
            raise ValueError(f"Y_train must be a 2-D one-hot matrix, but got shape {Y_train.shape}.")
        if F_train.shape[0] != Y_train.shape[0]:
            raise ValueError(
                f"F_train and Y_train have inconsistent sample sizes: "
                f"{F_train.shape[0]} vs {Y_train.shape[0]}."
            )

        y_train_label = self._labels_from_target(Y_train)

        # --------------------------------------------------------------
        # Base node: normalized basic firing strengths.
        # This corresponds to the feature mapping output before DET.
        # --------------------------------------------------------------
        Z_base = self._row_normalize(F_train)
        Z_base_pinv = np.linalg.pinv(Z_base, rcond=0.0)
        W_base = Z_base_pinv @ Y_train
        base_score = self._accuracy(Z_base, W_base, y_train_label)

        base_node = {
            "A": Z_base,
            "A_pinv": Z_base_pinv,
            "W": W_base,
            "score": base_score,
            "metas": [],
            "depth": 0,
        }

        self.elite_tree_ = []
        best_node = base_node
        self.best_score_ = base_score

        # --------------------------------------------------------------
        # DET settings.
        # m_l, m_u, V_max, T_max, and P_max in the manuscript.
        # --------------------------------------------------------------
        T_max = int(self.cfg.max_depth if max_depth is None else max_depth)
        V_max = int(self.cfg.elite_width)
        m_l = int(self.cfg.min_branch_nodes)
        m_u = int(self.cfg.max_branch_nodes)

        lower_size, upper_size = m_l, m_u
        branch_size = m_l
        previous_expansion_best_score = base_score
        no_improve_count = 0

        start_time = time.perf_counter()

        for depth in range(1, T_max + 1):
            # ----------------------------------------------------------
            # Step 1: Generate a new branch node phi_new with L_j nodes.
            # Each column in E_new is a composite fuzzy rule.
            # ----------------------------------------------------------
            E_new, meta_new = self._generate_composite_rule_batch(
                F_train,
                batch=branch_size,
            )

            # Store old elite layers before current update.
            # This avoids using newly inserted nodes again in the same depth.
            old_tree = [layer.copy() for layer in self.elite_tree_]

            # Highest score among all new candidates evaluated at this
            # expansion, denoted by \hat{v}_t in the manuscript.
            current_expansion_best_score = -np.inf

            # ----------------------------------------------------------
            # First layer:
            #   candidate = base node + phi_new.
            # This corresponds to initializing Phi^(1) by the new branch.
            # ----------------------------------------------------------
            node_depth_1 = self._train_combined_node(
                parent_node=base_node,
                E_new=E_new,
                meta_new=meta_new,
                Y_train=Y_train,
                y_train_label=y_train_label,
            )
            self._insert_elite_node(node_depth_1, layer_index=0, V_max=V_max)
            current_expansion_best_score = max(
                current_expansion_best_score,
                node_depth_1["score"],
            )

            # ----------------------------------------------------------
            # Higher layers:
            #   candidate = old elite branch + phi_new.
            # This implements the layer-wise elite expansion in DET.
            # ----------------------------------------------------------
            for layer_index, old_layer in enumerate(old_tree):
                for elite_node in old_layer:
                    deeper_node = self._train_combined_node(
                        parent_node=elite_node,
                        E_new=E_new,
                        meta_new=meta_new,
                        Y_train=Y_train,
                        y_train_label=y_train_label,
                    )
                    self._insert_elite_node(
                        deeper_node,
                        layer_index=layer_index + 1,
                        V_max=V_max,
                    )
                    current_expansion_best_score = max(
                        current_expansion_best_score,
                        deeper_node["score"],
                    )

            # ----------------------------------------------------------
            # Select global best branch according to training accuracy.
            # The test data are not used here.
            # ----------------------------------------------------------
            round_best_node = self._best_node_in_tree(default_node=base_node)
            if round_best_node["score"] > best_node["score"]:
                best_node = round_best_node
                self.best_score_ = best_node["score"]
                no_improve_count = 0
            else:
                no_improve_count += 1

            # ----------------------------------------------------------
            # Adaptive branch-size update.
            # Compare the best newly generated candidate with that from the
            # preceding expansion. This is separate from the global record.
            # ----------------------------------------------------------
            if (
                current_expansion_best_score
                > previous_expansion_best_score
            ):
                lower_size = branch_size
            else:
                upper_size = branch_size

            branch_size = int(np.floor((lower_size + upper_size) / 2.0))
            branch_size = max(m_l, min(m_u, branch_size))
            previous_expansion_best_score = current_expansion_best_score

            if no_improve_count >= self.cfg.patience:
                break

        self.enhancement_time = time.perf_counter() - start_time

        # --------------------------------------------------------------
        # Save the selected branch.
        # --------------------------------------------------------------
        self.W_ = best_node["W"]
        self.blocks_meta = best_node["metas"]
        self.S_expected_ = best_node["A"].shape[1]
        self.best_node_depth = best_node["depth"]
        self.best_node_total_nodes = len(best_node["metas"])

        return best_node["A"], best_node["A_pinv"], best_node["W"]

    def test(self, F_test: np.ndarray, Y_test: np.ndarray) -> float:
        """
        Evaluate the selected HDFBLS model on test data.

        Parameters
        ----------
        F_test : array, shape (N_test, R)
            Basic firing-strength matrix of test samples.
        Y_test : array, shape (N_test,) or (N_test, C)
            Test labels or one-hot encoded test labels.
        """
        if self.W_ is None:
            raise RuntimeError("Call train_enhancement_incremental before test.")

        F_test = np.asarray(F_test, dtype=np.float64)
        y_true = self._labels_from_target(Y_test)

        Z_test = self._row_normalize(F_test)

        E_cols = []
        for meta in self.blocks_meta:
            E_cols.append(self._evaluate_composite_rule(F_test, meta))

        if E_cols:
            E_test = np.concatenate(E_cols, axis=1)
            Z_test = np.concatenate([Z_test, E_test], axis=1)

        if Z_test.shape[1] != self.W_.shape[0]:
            raise ValueError(
                f"Shape mismatch: test matrix has {Z_test.shape[1]} columns, "
                f"but W_ expects {self.W_.shape[0]}."
            )

        y_pred = np.argmax(Z_test @ self.W_, axis=1)
        return float(np.mean(y_pred == y_true))

    # ------------------------------------------------------------------
    # Composite fuzzy rule generation
    # ------------------------------------------------------------------
    def _generate_composite_rule_batch(
        self,
        F: np.ndarray,
        batch: int,
    ) -> tuple[np.ndarray, list[dict[str, Any]]]:
        """
        Generate a branch node containing `batch` composite fuzzy rules.

        The inputs of this layer are the basic rule activations F.
        Each composite fuzzy rule follows the OR-AND structure described
        in the manuscript.
        """
        F = np.asarray(F, dtype=np.float64)
        N, M = F.shape

        centers = self._generate_fuzzy_centers()
        spread = 1.0

        ilfr = ILFR(
            in_dim=M,
            num_sam=N,
            center=centers,
            num_fuzzy_set=self.cfg.num_fuzzy_set,
        )
        UL = ilfr.fuzzify_input(F, spread=spread)

        E = np.empty((N, batch), dtype=np.float64)
        metas: list[dict[str, Any]] = []

        for node_id in range(batch):
            # CL selects linguistic terms for each basic rule activation.
            # DL disables unselected basic-rule dimensions.
            CL = self.rng.integers(
                0,
                2,
                size=(M, self.cfg.num_fuzzy_set),
                dtype=np.int64,
            )
            DL = self.rng.integers(0, 2, size=(M,), dtype=np.int64)

            h = ilfr.compute_activation(UL, CL, DL).reshape(N)
            E[:, node_id] = h

            metas.append({
                "CL": CL.copy(),
                "DL": DL.copy(),
                "center": np.asarray(centers, dtype=np.float64),
                "spread": float(spread),
            })

        return E, metas

    def _evaluate_composite_rule(
        self,
        F: np.ndarray,
        meta: dict[str, Any],
    ) -> np.ndarray:
        """Evaluate one composite fuzzy rule on new data."""
        F = np.asarray(F, dtype=np.float64)
        N, M = F.shape

        ilfr = ILFR(
            in_dim=M,
            num_sam=N,
            center=meta["center"],
            num_fuzzy_set=self.cfg.num_fuzzy_set,
        )
        UL = ilfr.fuzzify_input(F, spread=meta["spread"])
        h = ilfr.compute_activation(UL, meta["CL"].copy(), meta["DL"].copy())
        return h.reshape(N, 1)

    def _generate_fuzzy_centers(self) -> np.ndarray:
        """
        Generate centers for five linguistic fuzzy sets on [0,1].

        The five intervals correspond to:
        Very Low, Low, Medium, High, and Very High.
        """
        edges = np.linspace(0.0, 1.0, self.cfg.num_fuzzy_set + 1)
        centers = self.rng.uniform(edges[:-1], edges[1:])
        return centers.astype(np.float64)

    # ------------------------------------------------------------------
    # DET utilities
    # ------------------------------------------------------------------
    def _insert_elite_node(
        self,
        new_node: dict[str, Any],
        layer_index: int,
        V_max: int,
    ) -> None:
        """
        Insert a candidate into one elite layer.

        If the layer is not full, append the candidate.
        If the layer is full, replace the weakest branch only when
        the candidate has a higher score.
        """
        while len(self.elite_tree_) <= layer_index:
            self.elite_tree_.append([])

        layer = self.elite_tree_[layer_index]

        if len(layer) < V_max:
            layer.append(new_node)
        elif new_node["score"] > layer[-1]["score"]:
            layer[-1] = new_node

        layer.sort(key=lambda node: node["score"], reverse=True)

    def _best_node_in_tree(self, default_node: dict[str, Any]) -> dict[str, Any]:
        """Return the best branch node retained in the current elite tree."""
        best = default_node
        for layer in self.elite_tree_:
            if layer and layer[0]["score"] > best["score"]:
                best = layer[0]
        return best

    def _train_combined_node(
        self,
        parent_node: dict[str, Any],
        E_new: np.ndarray,
        meta_new: list[dict[str, Any]],
        Y_train: np.ndarray,
        y_train_label: np.ndarray,
    ) -> dict[str, Any]:
        """
        Train a candidate branch-node combination.

        The new branch is appended to the parent branch, and the output
        weights are updated by Greville incremental pseudoinverse.
        """
        A_parent = parent_node["A"]
        W_parent = parent_node["W"]
        A_pinv_parent = parent_node["A_pinv"]

        A_new, A_pinv_new, W_new = self._greville_block_append(
            Z=A_parent,
            Y=Y_train,
            E=E_new,
            Z_pinv=A_pinv_parent,
            W=W_parent,
        )

        score = self._accuracy(A_new, W_new, y_train_label)

        return {
            "A": A_new,
            "A_pinv": A_pinv_new,
            "W": W_new,
            "score": score,
            "metas": parent_node["metas"] + meta_new,
            "depth": parent_node["depth"] + 1,
        }

    # ------------------------------------------------------------------
    # Numerical utilities
    # ------------------------------------------------------------------
    def _row_normalize(self, F: np.ndarray) -> np.ndarray:
        """
        Normalize basic firing strengths row by row.

        This corresponds to normalized basic-rule activations used as
        the base representation of HDFBLS.
        """
        F = np.asarray(F, dtype=np.float64)
        row_sum = np.sum(F, axis=1, keepdims=True)
        return F / row_sum

    @staticmethod
    def _greville_block_append(
        Z: np.ndarray,
        Y: np.ndarray,
        E: np.ndarray,
        Z_pinv: Optional[np.ndarray] = None,
        W: Optional[np.ndarray] = None,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """
        Append a feature block E to Z and update pseudoinverse/output weights.
        """
        Z = np.asarray(Z, dtype=np.float64)
        Y = np.asarray(Y, dtype=np.float64)
        E = np.asarray(E, dtype=np.float64)

        if Z_pinv is None:
            Z_pinv = np.linalg.pinv(Z, rcond=0.0)
        if W is None:
            W = Z_pinv @ Y

        D = Z_pinv @ E
        C = E - Z @ D

        if np.linalg.matrix_rank(C) > 0:
            B_T = np.linalg.pinv(C, rcond=0.0)
        else:
            K = D.T @ D
            K.flat[:: K.shape[0] + 1] += 1.0
            RHS = D.T @ Z_pinv
            try:
                B_T = np.linalg.solve(K, RHS)
            except np.linalg.LinAlgError:
                B_T = np.linalg.pinv(K, rcond=0.0) @ RHS

        Z_pinv_new = np.vstack([Z_pinv - D @ B_T, B_T])
        W_new_part = B_T @ Y
        W_new = np.vstack([W - D @ W_new_part, W_new_part])
        Z_new = np.concatenate([Z, E], axis=1)

        return Z_new, Z_pinv_new, W_new

    @staticmethod
    def _labels_from_target(Y: np.ndarray) -> np.ndarray:
        Y = np.asarray(Y)

        if Y.ndim == 2 and Y.shape[1] > 1:
            return np.argmax(Y, axis=1)

        y = Y.reshape(-1)
        if np.array_equal(np.unique(y), np.array([-1, 1])):
            return (y > 0).astype(int)

        return y.astype(int)

    @staticmethod
    def _accuracy(A: np.ndarray, W: np.ndarray, y_true: np.ndarray) -> float:
        y_pred = np.argmax(A @ W, axis=1)
        return float(np.mean(y_pred == y_true))
